- name: Get exporter binaries
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp

- name: Unarchive exporter
  unarchive:
    remote_src: yes
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp

- name: Create node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present
  become: yes 

- name: Create exporter user
  user:
    name: "{{ node_exporter_user }}"
    state: present
    group: "{{ node_exporter_group }}"
    shell: /bin/false
    create_home: false
  become: yes

- name: Create config directory
  file:
    path: /etc/node_exporter
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0644'
  become: yes

- name: Move binaries to /usr/bin
  copy: 
    remote_src: yes
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/bin/
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0755"
  become: yes

- name: Create service definition 
  template:
    src: node_exporter.j2
    dest: "{{ service_directory }}/node_exporter.service"
  become: yes

- name: configure systemd to use service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: node_exporter.service
  become: yes