- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: yes

- name: Install OpenJDK Java
  apt: name=openjdk-11-jdk update_cache=yes state=present
  become: yes